# file: postgresql/tasks/extensions.yml

# Loot at file defaults/main.yml for default values

- import_tasks: extensions/contrib.yml
  when: postgresql_ext_install_contrib

- import_tasks: extensions/dev_headers.yml
  when: postgresql_ext_install_dev_headers
